remote_theme: mmistakes/minimal-mistakes@4.24.0

minimal_mistakes_skin: "default"

title: Mark Wragg
subtitle: Windows, Automation, Powershell, Pester, Chef, AWS, Azure
name: Mark Wragg

description: UK based DevOps blogger.

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_overlay_excerpt: false
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

include: ["_pages"]

logo: /content/images/MarkWragg.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name: Mark Wragg
  email: mark@wragg.io

# Format of the permalinks
permalink: /:categories/:title/

# Pagination configuration (used by the `blog` layout)
paginate: 10
paginate_path: /:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache